# Generated by Django 4.2.4 on 2023-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='ProfileImage/'),
        ),
    ]
